# Generated by Django 5.0.3 on 2024-04-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='github_profile',
            new_name='github_ID',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='linkedin_profile',
            new_name='linkedin_ID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='language_proficiency',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='portfolio_profile',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='students', to='Lexicon_App.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_details',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.ManyToManyField(to='Lexicon_App.skillset'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(to='Lexicon_App.skillset'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
