# Generated by Django 5.0.3 on 2024-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Skillset',
        ),
    ]
