# Generated by Django 5.0.3 on 2024-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0002_remove_student_skills_alter_student_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(to='Lexicon_App.skillset'),
        ),
    ]
