# Generated by Django 4.2.7 on 2024-04-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0002_remove_student_course_student_course'),
        ('Lexicon_App', '0002_student_profile_picture'),
    ]

    operations = [
    ]
