# Generated by Django 5.0.3 on 2024-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0003_rename_github_profile_student_github_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_ID',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='students', to='Lexicon_App.course'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.ManyToManyField(to='Lexicon_App.skillset'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(to='Lexicon_App.skillset'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
