# Generated by Django 4.2.7 on 2024-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0003_merge_20240412_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='students', to='Lexicon_App.course'),
        ),
    ]
