# Generated by Django 4.2.7 on 2024-04-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lexicon_App', '0003_skillset_student_skills'),
        ('Lexicon_App', '0004_skillset_remove_course_student_id_student_course_and_more'),
    ]

    operations = [
    ]
